DEFINES+=PROJECT_CONF_H=\"project-conf.h\"
CONTIKI_PROJECT = cc26xx-demo

TARGET = srf06-cc26xx
BOARD = launchpad/cc2650

all: $(CONTIKI_PROJECT)

CONTIKI_WITH_IPV6 = 1

CONTIKI = /home/samuel/contiki2/contiki
include $(CONTIKI)/Makefile.include
